-- Standard Function 표준함수

-- dual table : 가상 테이블 -> 결과 확인용 임시 테이블
SELECT 1 FROM DUAL;
SELECT 'A' FROM DUAL;
SELECT '가' FROM DUAL;
SELECT 23*34 FROM DUAL;



-- 문자 함수
-- CHR( N ) : ASCII 값을 문자로 변환하는 함수
SELECT CHR(65) FROM DUAL; -- A
SELECT CHR(49) FROM DUAL; -- 1
SELECT CHR(97) FROM DUAL; -- a

-- "안녕하세요" + "건강하세요" = "안녕하세요건강하세요" <-- 자바
--     || == +   <OR연산자가 아닌 문자열끼리 연결할때 사용>
SELECT '안녕하세요' || '건강하세요' FROM DUAL;
SELECT '내 점수는' || CHR(65) || '입니다' FROM DUAL;

-- LPAD(RPAD) : 빈칸을 지정문자로 채운다
SELECT LPAD('BBB', 10) FROM DUAL;
SELECT RPAD('BBB', 10) FROM DUAL;

SELECT LPAD('BBB', 10, '-') FROM DUAL;
SELECT LPAD('BBB', 10, '0') FROM DUAL;

-- INSTR == indexOf(c) == 2  abcd  <인덱스의 값을 넘겨준다>
SELECT INSTR('123ABC456ABC', 'A') FROM DUAL;
SELECT INSTR('123ABC456ABC', 'A', 6) FROM DUAL; -- 6번째 다음에 있는 'A'를 찾는다
SELECT INSTR('123ABC456ABC', 'A' , 6, 1) FROM DUAL;-- 6번째 다음에 있는 첫번째'A'
SELECT INSTR('123ABC456ABCABC', 'A' , 6, 2) FROM DUAL;-- 6번째 다음에 있는 두번째'A'
SELECT INSTR('123ABC456ABC', 'D') FROM DUAL;-- 없으면 0

-- REPLACE : 문자열 치환
SELECT REPLACE('AAAAABC', 'A') FROM DUAL;
SELECT REPLACE('AAAAABC', 'A', 'a') FROM DUAL;
SELECT REPLACE('AAAAABC', 'AA', 'a') FROM DUAL;

-- TRANSLATE : 문자치환
SELECT TRANSLATE('AAAAABC', 'A', 'a') FROM DUAL;
SELECT TRANSLATE('AAAAABC', 'AA', 'a') FROM DUAL; -- AA에 뒤에 A가 무시 문자만 취급

-- 숫자
-- 올림
SELECT CEIL(13.1) FROM DUAL;
-- 내림
SELECT FLOOR(13.9) FROM DUAL;
-- 승수
SELECT POWER(3, 2) FROM DUAL;
-- 반올림
SELECT ROUND(13.5) FROM DUAL;
SELECT ROUND(13.4) FROM DUAL;

-- 부호 양수1, 0 ,음수 -1
-- SIGN
SELECT SIGN(12) FROM DUAL; -- 1
SELECT SIGN(0) FROM DUAL; -- 0
SELECT SIGN(-6) FROM DUAL; -- -1

-- 버림
-- TRUNC
SELECT TRUNC(12.34567) FROM DUAL;
SELECT TRUNC(12.34567, 2) FROM DUAL; -- 소수점 2번째 자리까지는 살림
SELECT TRUNC(12.34567, -1) FROM DUAL; -- 일의 자리까지 버림

-- ASCII 
SELECT ASCII('A') FROM DUAL;
SELECT CHR(65) FROM DUAL;
-- 변환 함수
-- TO_CHAR
-- DATE -> VARCHAR2
SELECT to_char(SYSDATE) FROM DUAL; -- 문자열

SELECT to_char(SYSDATE, 'YYYY-MM-DD-HH-MI-SS') FROM DUAL;
SELECT to_char(SYSDATE, 'YYYY/MM/DD HH:MI:SS') FROM DUAL;
SELECT to_char(TO_DATE(SYSDATE,'YYYY/MM/DD HH:MI:SS'), 'YYYY/MM/DD HH:MI:SS') FROM DUAL;
SELECT SYSDATE FROM DUAL; 

SELECT TO_CHAR(10000000, '$999,999,999,999') FROM DUAL;

-- TO_DATE
-- VARCJAR2 -> DATE
SELECT TO_DATE('20201205') FROM DUAL;
SELECT TO_DATE('20201205', 'YYYYMMDD') FROM DUAL;
SELECT TO_DATE('12052020', 'MMDDYYYY') FROM DUAL;

-- TO_NUMBER    VARCHAR2 -> NUMBER      Integer.parseInt()
SELECT to_number(('123') + 1) FROM DUAL;
SELECT '123' + 1 FROM DUAL;

-- LAST_DAY
SELECT LAST_DAY('20/11/01') FROM DUAL;

-- SUBSTR == ABCdef  subString(1, 3)  ->  자바일 경우 BC subString(4)->ef
SELECT SUBSTR('ABCDEFG',3) FROM dual;  -- > CDEFG 몇번째 문자
SELECT SUBSTR('ABCDEFG',3, 3) FROM dual; --> CDE 몇번째 몇개문자

