CREATE OR REPLACE PROCEDURE BOOK_DISP
--매개변수 선언부 : ( )안에 작성, 구분문자  콤마사용(,) 
(
    IN_BOOKID IN NUMBER
)
AS -- 변수 선언부(AS 또는 IS ~ BEGIN 문 사이) 
    V_BOOKID NUMBER(2);
    V_BOOKNAME VARCHAR2(40);
    V_PUBLISHER VARCHAR2(40);
    V_PRICE NUMBER(8);
BEGIN
SELECT BOOKID, BOOKNAME, PUBLISHER,PRICE
        INTO V_BOOKID, V_BOOKNAME, V_PUBLISHER, V_PRICE
    FROM BOOK
    WHERE BOOKID = IN_BOOKID;
    
     DBMS_OUTPUT.PUT_LINE(V_BOOKID || ' , ' || V_BOOKNAME || ' , ' ||
            V_PUBLISHER   || ' , ' || V_PRICE  );

END;
-- public int procedure1(int param, String param2)
CREATE OR REPLACE PROCEDURE PROCEDURE1 (
  PARAM1 IN VARCHAR2 
, PARAM3 OUT VARCHAR2 
, PARAM2 IN OUT VARCHAR2 
) AS 
BEGIN
  NULL;
END PROCEDURE1;