/* **** 시퀀스(SEQUENCE)
SEQUENCE : DB에서 제공하는 자동채번 객체
생성 : CREATE SEQUENCE 시퀀스명;
삭제 : DROP SEQUENCE 시퀀스명;

시퀀스명.NEXTVAL : 시퀀스 번호(값) 생성
시퀀스명.CURRVAL : 현재 시퀀스값 확인(NEXTVAL 한 번 이상 실행 후)
****************************/

CREATE SEQUENCE "SEQUENCE1" 
MINVALUE 1 MAXVALUE 9999999999999999999999999999 
INCREMENT BY 1
START WITH 1
CACHE 20 NOORDER  NOCYCLE;
----------------------------
SELECT SEQUENCE1.NEXTVAL FROM DUAL;
------------------------------
SELECT * FROM BOOK;
SELECT MAX(BOOKID), MAX(BOOKID) +1  FROM BOOK;
SELECT MAX(AAA), NVL(MAX(AAA),0) +1  FROM AAA; -- 데이터가 없을때
-------------------
-- BOOK 테이블에 INSERT 작업, BOOKID 최대값 +1
INSERT INTO BOOK
    (BOOKID, BOOKNAME, PUBLISHER, PRICE)
VALUES ((SELECT NVL(MAX(BOOKID),0) + 1 FROM BOOK),
        'MAX(BOOKID) + 1', 'ITBOOK', 20000);
        COMMIT;
SELECT * FROM BOOK ORDER BY BOOKID DESC;
------------------------------------------------
--시퀀스 사용(시작번호 지정 50, NOCACHE)
CREATE SEQUENCE SEQ_BOOK
START WITH 50
INCREMENT BY 1 -- 생략시 동일 DEFAULT 1씩 증가
NOCACHE -- 캐시 사용 안함
;
SELECT SEQ_BOOK.NEXTVAL FROM DUAL;
-------------------------------
-- BOOK 테이블에 시퀀스 사용 입력 처리
INSERT INTO BOOK
    (BOOKID, BOOKNAME, PUBLISHER, PRICE)
VALUES (SEQ_BOOK.NEXTVAL,
        'SEQ_BOOK.NEXTVAL 적용', 'ITBOOK', 20000);
        COMMIT;
SELECT * FROM BOOK ORDER BY BOOKID DESC;