CREATE TABLE AAA(AAA NUMBER);
DROP TABLE AAA;
-- (MDGUEST에서) CUSTOMER 테이블 SELECT, UPDATE
SELECT * FROM MADANG.CUSTOMER;
UPDATE MADANG.CUSTOMER
    SET PHONE = '010-1111-2222'
WHERE NAME = '박세리';
DELETE FROM MADANG.CUSTOMER WHERE NAME = '박세리';